# Generated by Django 4.0.4 on 2022-04-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_freetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField()),
                ('firstName', models.CharField(max_length=150, null=True)),
                ('department', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
    ]
